
  version: '3.8'
  services:
    ecommerce_service_provider:
      container_name: weather
      build:
        context: .
        dockerfile: Dockerfile
      environment:
        - SPRING_DATASOURCE_URL=jdbc:mysql://localhost:3306/weatherDb
        - SPRING_DATASOURCE_USERNAME=root
        - SPRING_DATASOURCE_PASSWORD=ozlam2002
      ports:
        - "8087:8080"
      restart: unless-stopped
      volumes:
        - db_weather:/var/lib/mysql

    mysql_provider_ecommerce:
      image: mysql:latest
      container_name: weather_mysql
      ports:
        - "3307:3306"
      restart: unless-stopped
      environment:
        - MYSQL_DATABASE=weatherDb
        - MYSQL_USER=root
        - MYSQL_PASSWORD=ozlam2002
        - MYSQL_ROOT_PASSWORD=ozlam2002
      volumes:
        - db_weather:/var/lib/mysql

  volumes:
    db_weather:
      driver: local
